import re
from pylatex import Document, Section, Command, Itemize
from pylatex.table import Tabularx
from pylatex.utils import NoEscape
from pylatex.utils import bold

class LatexAgent:
    def __init__(self):
        pass

    def _parse_and_add_content(self, doc, text: str):
        """Parses content for special formats like tables and figures."""
        text = re.sub(r'(?m)^\s*\*\*(.*?)\*\*\s*$', r'\\subsection*{\1}', text)
        text = re.sub(r'\*\*(.*?)\*\*', r'\\textbf{\1}', text)

        pattern = re.compile(r'((?:\|.*\|(?:\r\n|\n|\r))+)|(\[CITE:(.*?)\])')
        
        last_pos = 0
        for match in pattern.finditer(text):
            start, end = match.span()
            
            pre_text = text[last_pos:start]
            if pre_text.strip():
                doc.append(NoEscape(pre_text))
            
            markdown_table, cite_placeholder, cite_key = match.groups()

            if markdown_table:
                lines = [l.strip() for l in markdown_table.strip().split('\n') if l.strip()]
                if len(lines) < 2 or '---' not in lines[1]:
                    doc.append(NoEscape(markdown_table)) 
                    continue
                
                header = [h.strip() for h in lines[0].strip('|').split('|')]
                col_format = 'l' + 'X' * (len(header) - 1)
                
                doc.append(NoEscape(r'\begin{center}'))
                with doc.create(Tabularx(col_format, width_argument=NoEscape(r'\textwidth'))) as table:
                        table.add_row(header, mapper=[bold])
                        table.add_hline()
                        for line in lines[2:]:
                            row = [r.strip() for r in line.strip('|').split('|')]
                            if len(row) == len(header):
                                table.add_row(row)
                doc.append(NoEscape(r'\end{center}'))
            
            elif cite_placeholder:
                doc.append(NoEscape(r'\cite{' + cite_key + '}'))

            last_pos = end
            
        remaining_text = text[last_pos:]
        if remaining_text.strip():
            doc.append(NoEscape(remaining_text))

    def generate_latex(self, research_data: dict, filename: str = "research_paper"):
        """
        Generates a LaTeX document and compiles it to PDF.
        """
        geometry_options = {"tmargin": "2cm", "lmargin": "2cm", "rmargin": "2cm", "bmargin": "2cm"}
        doc = Document(geometry_options=geometry_options)

        doc.preamble.append(NoEscape(r'\usepackage{tabularx}'))
        doc.preamble.append(NoEscape(r'\usepackage{booktabs}'))
        doc.preamble.append(NoEscape(r'\usepackage{hyperref}'))
        doc.preamble.append(NoEscape(r'\hypersetup{colorlinks=true, linkcolor=blue, filecolor=magenta, urlcolor=cyan, breaklinks=true}'))

        doc.preamble.append(Command('title', research_data.get('title', 'Research Paper')))
        doc.preamble.append(Command('author', 'Generated by Research Agent'))
        doc.preamble.append(Command('date', NoEscape(r'\today')))
        
        doc.append(NoEscape(r'\maketitle'))

        if research_data.get('abstract'):
            doc.append(Command('begin', 'abstract'))
            self._parse_and_add_content(doc, research_data['abstract'])
            doc.append(Command('end', 'abstract'))

        if research_data.get('introduction'):
            with doc.create(Section('Introduction')):
                self._parse_and_add_content(doc, research_data['introduction'])

        if research_data.get('literature_review'):
            with doc.create(Section('Literature Review')):
                self._parse_and_add_content(doc, research_data['literature_review'])

        if research_data.get('methodology'):
            with doc.create(Section('Methodology')):
                self._parse_and_add_content(doc, research_data['methodology'])

        if research_data.get('results'):
            with doc.create(Section('Results')):
                self._parse_and_add_content(doc, research_data['results'])

        if research_data.get('discussion'):
            with doc.create(Section('Discussion')):
                self._parse_and_add_content(doc, research_data['discussion'])

        if research_data.get('conclusion'):
            with doc.create(Section('Conclusion')):
                self._parse_and_add_content(doc, research_data['conclusion'])

        if research_data.get('references'):
            doc.append(NoEscape(r'\begin{thebibliography}{99}'))
            for ref in research_data['references']:
                doc.append(NoEscape(r'\bibitem{' + ref['key'] + '} ' + ref['ref']))
            doc.append(NoEscape(r'\end{thebibliography}'))

        try:
            doc.generate_pdf(filename, clean_tex=False)
            return f"{filename}.pdf"
        except Exception as e:
            doc.generate_tex(filename)
            return f"{filename}.tex"